return {
  herojugglenaught = {
    unitname = [[herojugglenaught]],
    name                   = [[L.O.B.I.X.]],
    description            = [[People who live in glass housees shouldn't throw stones. This guy doesn't get it though...]],
    acceleration           = 0.3,
    brakeRate              = 1.8,
    buildPic               = [[jumpsumo.png]],
    canGuard               = true,
    canMove                = true,
    canPatrol              = true,
    canManualFire          = true,

    category               = [[LAND]],
    collisionVolumeOffsets  = [[0 0 0]],
    collisionVolumeScales   = [[64 64 64]],
    collisionVolumeType     = [[ellipsoid]],
    selectionvolumeoffsets  = [[0 -16 0]],
    selectionVolumeScales   = [[105 105 105]],
    selectionVolumeType     = [[ellipsoid]],
    corpse              = [[DEAD]],

    customParams         = {
      hero               = true,
      bait_level_default = 0,
      can_target_allies  = 1,
      canjump            = 1,
      jump_range         = 360,
      jump_height        = 110,
      jump_speed         = 6,
      jump_delay         = 30,
      jump_reload        = 15,
      jump_from_midair   = 0,
      jump_rotate_midair = 0,
      aimposoffset   = [[0 6 0]],
      midposoffset   = [[0 6 0]],
      modelradius    = [[32]],
      lookahead      = 120,
      selection_scale = 1.22,
    },
  idleAutoHeal = 250,
  idleTime = 200,
  explodeAs           = [[BIG_UNIT]],
  footprintX          = 4,
  footprintZ          = 4,
  health              = 10000, --13500
  iconType            = [[t3jumpjetriot]],
  leaveTracks         = true,
  maxSlope            = 36,
  maxWaterDepth       = 22,
  metalCost = 1500,
  movementClass       = [[KBOT4]],
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE SUB]],
  objectName          = [[m-9.s3o]],
  onoffable           = true,
  script              = [[herojugglenaught.lua]],
  selfDestructAs      = [[BIG_UNIT]],

  sfxtypes            = {

    explosiongenerators = {
      [[custom:sumosmoke]],
      [[custom:BEAMWEAPON_MUZZLE_ORANGE]],
    },

  },
  sightEmitHeight     = 60,
  sightDistance       = 480,
  speed               = 34.5,
  trackOffset         = 0,
  trackStrength       = 8,
  trackStretch        = 1,
  trackType           = [[crossFoot]],
  trackWidth          = 66,
  turnRate            = 600,
  upright             = false,
  workerTime          = 0,

  weapons             = {

    {
      def                = [[FAKELASER]],
      mainDir            = [[0 0 1]],
      maxAngleDif        = 30,
    },
    {
      def                = [[GRAVITY_NEG]],
      badTargetCategory  = [[]],
      onlyTargetCategory = [[FIXEDWING HOVER SWIM LAND SHIP GUNSHIP]],
      mainDir            = [[-1 0 0]],
      maxAngleDif        = 222,
    },
    {
      def                = [[GRAVITY_NEG]],
      badTargetCategory  = [[]],
      onlyTargetCategory = [[FIXEDWING HOVER SWIM LAND SHIP GUNSHIP]],
      mainDir            = [[1 0 0]],
      maxAngleDif        = 222,
    },
    {
      def                = [[GRAVITY_POS]],
      badTargetCategory  = [[]],
      onlyTargetCategory = [[FIXEDWING HOVER SWIM LAND SHIP GUNSHIP]],
      mainDir            = [[-1 0 0]],
      maxAngleDif        = 222,
    },
    {
      def                = [[GRAVITY_POS]],
      badTargetCategory  = [[]],
      onlyTargetCategory = [[FIXEDWING HOVER SWIM LAND SHIP GUNSHIP]],
      mainDir            = [[1 0 0]],
      maxAngleDif        = 222,
    },
    {
      def                = [[LANDING]],
      badTargetCategory  = [[]],
      mainDir            = [[1 0 0]],
      maxAngleDif        = 0,
      onlyTargetCategory = [[]],
    },
    {
      def                = [[METEOR]],
      badTargetCategory  = [[MOBILE]],
      onlyTargetCategory = [[SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP]],
    },
    {
      def                = [[LASER]],
      --mainDir            = [[0 0 0]],
      maxAngleDif        = 222,
    },
  },


  weaponDefs          = {

    FAKELASER     = {
      name                    = [[Fake Laser]],
      areaOfEffect            = 12,
      beamTime                = 0.1,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,

      customParams            = {
        bogus = 1,
      },

      damage                  = {
        default = 0,
      },

      duration                = 0.1,
      edgeEffectiveness       = 0.99,
      explosionGenerator      = [[custom:flash1green]],
      fireStarter             = 70,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      largeBeamLaser          = true,
      laserFlareSize          = 5.53,
      minIntensity            = 1,
      noSelfDamage            = true,
      proximityPriority       = 10,
      range                   = 500,
      reloadtime              = 0.1,
      rgbColor                = [[0 1 0]],
      soundStart              = [[weapon/laser/laser_burn5]],
      soundTrigger            = true,
      texture1                = [[largelaser]],
      texture2                = [[flare]],
      texture3                = [[flare]],
      texture4                = [[smallflare]],
      thickness               = 5.53,
      tolerance               = 10000,
      turret                  = false,
      weaponType              = [[BeamLaser]],
      weaponVelocity          = 900,
    },

    GRAVITY_NEG = {
      name                    = [[Attractive Gravity]],
      areaOfEffect            = 8,
      avoidFriendly           = false,
      burst                   = 60,
      burstrate               = 0.033,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,
      --commandFire = true,

      customParams            = {
        impulse = [[-150]],

        light_color = [[0.33 0.33 1.28]],
        light_radius = 140,
      },

      damage                  = {
        default = 0.001,
        planes  = 0.001,
      },

      duration                = 0.0333,
      explosionGenerator      = [[custom:NONE]],
      heightMod               = 0.4,
      impactOnly              = true,
      intensity               = 0.7,
      interceptedByShieldType = 0,
      noSelfDamage            = true,
      proximityPriority       = -15,
      range                   = 440,
      reloadtime              = 3, --0.2,
      rgbColor                = [[0 0 1]],
      rgbColor2               = [[1 0.5 1]],
      size                    = 2,
      soundStart              = [[weapon/gravity_fire]],
      soundTrigger            = true,
      thickness               = 4,
      tolerance               = 5000,
      turret                  = true,
      weaponType              = [[LaserCannon]],
      weaponVelocity          = 2200,
    },


    GRAVITY_POS = {
      name                    = [[Repulsive Gravity]],
      areaOfEffect            = 8,
      avoidFriendly           = false,
      burst                   = 60,
      burstrate               = 0.033,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,
      --commandFire = true,

      customParams            = {
        impulse = [[150]],

        light_color = [[0.85 0.2 0.2]],
        light_radius = 140,
      },

      damage                  = {
        default = 0.001,
        planes  = 0.001,
      },

      duration                = 0.0333,
      explosionGenerator      = [[custom:NONE]],
      heightMod               = 0.4,
      impactOnly              = true,
      intensity               = 0.7,
      interceptedByShieldType = 0,
      noSelfDamage            = true,
      proximityPriority       = 15,
      range                   = 440,
      reloadtime              = 3, --0.2,
      rgbColor                = [[1 0 0]],
      rgbColor2               = [[1 0.5 1]],
      size                    = 2,
      soundStart              = [[weapon/gravity_fire]],
      soundTrigger            = true,
      thickness               = 4,
      tolerance               = 5000,
      turret                  = true,
      weaponType              = [[LaserCannon]],
      weaponVelocity          = 2200,
    },

    LANDING = {
      name                    = [[Jugglenaut Landing]],
      areaOfEffect            = 340,
      scarDiameter            = 340,
      canattackground         = false,
      craterBoost             = 4,
      craterMult              = 6,

      damage                  = {
        default = 1001.1,
        planes  = 1001.1,
      },

      edgeEffectiveness       = 0,
      explosionGenerator      = [[custom:land_small]],
      impulseBoost            = 0.5,
      impulseFactor           = 1,
      interceptedByShieldType = 1,
      noSelfDamage            = true,
      range                   = 5,
      reloadtime              = 13,
      scarIndices             = Shared.SCAR_SET.SUMO,
      soundHit                = [[krog_stomp]],
      soundStart              = [[krog_stomp]],
      soundStartVolume        = 3,
      turret                  = false,
      weaponType              = [[Cannon]],
      weaponVelocity          = 5,

      customParams            = {
        hidden = true
      }
    },

     LASER = {
      name                    = [[Light Laserbeam]],
      areaOfEffect            = 8,
      avoidFeature            = false,
      beamTime                = 4/30,
      collideFriendly         = false,
      coreThickness           = 0.3,
      craterBoost             = 0,
      craterMult              = 0,
      --cylinderTargeting     = 1,

      customparams = {
        stats_hide_damage = 1, -- continuous laser
        stats_hide_reload = 1,
        
        light_color = [[1 0.25 0.25]],
        light_radius = 175,
        
        combatrange = 240,
      },

      damage                  = {
        default = 8.1,
      },

      explosionGenerator      = [[custom:flash1red]],
      --heightMod             = 0.5,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      largeBeamLaser          = true,
      laserFlareSize          = 2,
      minIntensity            = 1,
      noSelfDamage            = true,
      range                   = 500,
      reloadtime              = 4/30,
      rgbColor                = [[1 0 0]],
      soundStart              = [[weapon/laser/laser_burn9]],
      sweepfire               = false,
      texture1                = [[largelaser]],
      texture2                = [[flare]],
      texture3                = [[flare]],
      texture4                = [[smallflare]],
      thickness               = 2,
      tolerance               = 2000,
      turret                  = true,
      weaponType              = [[BeamLaser]],
    },


    METEOR = {
      name = [[Meteor]],
      commandFire = true,
      alphaDecay = 0.12,
      areaOfEffect = 250,
      avoidGround=false,
      avoidFriendly=false,
      avoidFeature=false,
      avoidNeutral=false,
      burst = 3,
      burstrate = 0.5,
      bouncerebound = 0.12,
      bounceslip = 1,
      cegTag = [[METEOR_TAG]],

      craterBoost = 0,
      craterMult = 0,
      customParams = { meteor = true, accuracy = 250,},
      damage = {default = 1500},
      explosionGenerator = [[custom:av_tess]],
      fireStarter = 70,
      flightTime = 30,
      groundbounce = 0,
      impactOnly = false,
      impulseBoost = 250,
      impulseFactor = 0.5,
      interceptedByShieldType = 2,
      model = [[asteroid.s3o]],
      projectiles = 1,
      noSelfDamage = true,
      range = 1000,
      reloadtime = 30,
      smokeTrail = false,
      soundHitVolume = 8,
      soundHit = [[weapon/cannon/supergun_bass_boost]],
      soundStartVolume = 7,
      startVelocity = 300,
      sprayangle = 3200,--1600,
      stages = 32,
      tolerance = 4096,
      tracks = false,
      turnRate = 56000,
      turret = true,
      weaponAcceleration = 300,
      weaponType = [[MissileLauncher]],
      weaponVelocity = 400,
      wobble = 0,
      dance = 0
    },


    -- METEOR      = {
    --   name                    = [[Meteor]],
    --   accuracy                = 700,
    --   alwaysVisible           = 1,
    --   areaOfEffect            = 256,
    --   avoidFriendly           = false,
    --   avoidFeature            = false,
    --   avoidGround             = false,
    --   cegTag                  = [[METEOR_TAG]],
    --   collideFriendly         = true,
    --   craterBoost             = 3,
    --   craterMult              = 6,
    --   commandFire = true,

    --   customParams              = {
    --     light_color = [[2.4 1.5 0.6]],
    --     light_radius = 600,

    --     --spawns_name = "asteroid_dead",
    --     spawns_feature = 0,

    --     gatherradius     = [[240]],
    --     smoothradius     = [[120]],
    --     smoothmult       = [[0.5]],
    --     movestructures   = [[0.5]],
    --     quickgather      = [[1]],
    --     meteor = true,
    --   },

    --   damage                  = {
    --     default = 1600,
    --   },

    --   edgeEffectiveness       = 0.8,
    --   explosionGenerator      = [[custom:av_tess]],
    --   fireStarter             = 70,
    --   flightTime              = 30,
    --   impulseBoost            = 250,
    --   impulseFactor           = 0.5,
    --   interceptedByShieldType = 2,
    --   noSelfDamage            = false,
    --   model                   = [[asteroid.s3o]],
    --   range                   = 8800,
    --   reloadtime              = 1.2,
    --   smokeTrail              = true,
    --   smokePeriod             = 10,
    --   smokeSize               = 80,
    --   soundHit                = [[weapon/cannon/supergun_bass_boost]],
    --   startVelocity           = 1500,

    --   textures                = {
    --     [[null]],
    --     [[largedarksmoketrail]],
    --     [[null]],
    --   },

    --   turret                  = true,
    --   turnrate                = 2000,
    --   weaponAcceleration      = 2000,
    --   weaponType              = [[MissileLauncher]],
    --   weaponVelocity          = 1600,
    --   wobble                  = 5500,
    -- },
  },


  featureDefs         = {

    DEAD = {
      blocking         = true,
      featureDead      = [[HEAP]],
      footprintX       = 3,
      footprintZ       = 3,
      object           = [[m-9_wreck.s3o]],
    },


    HEAP = {
      blocking         = false,
      footprintX       = 3,
      footprintZ       = 3,
      object           = [[debris3x3a.s3o]],
    },

  },
  }
}
